[project]
name = "ipython_venv"
version = "0.1.0"
description = "An IPython sandbox"
dependencies = [
    "ipython>=8.22.2",
    "plumbum>=1.8.2",
    "exif>=1.6.0",
    "rich>=14.1.0",
    "icecream>=2.1.8",
    "pillow>=12.0.0",
]
requires-python = ">= 3.12"

